services:
  postgres:
    image: postgres:16
    container_name: smartlogix-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  inventario-service:
    build: ./backend/inventario-service
    container_name: inventario-service
    ports:
      - "8001:8001"
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: inventario
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

  pedidos-service:
    build: ./backend/pedidos-service
    container_name: pedidos-service
    ports:
      - "8002:8002"
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: pedidos
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

  envios-service:
    build: ./backend/envios-service
    container_name: envios-service
    ports:
      - "8003:8003"
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: envios
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

  usuarios-service:
    build: ./backend/usuarios-service
    container_name: usuarios-service
    ports:
      - "8004:8004"
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: usuarios
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

  gateway-service:
    build: ./backend/gateway-service
    container_name: gateway-service
    ports:
      - "8443:8443"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      SSL_KEYSTORE_PASSWORD: ${SSL_KEYSTORE_PASSWORD}
      SPRING_PROFILES_ACTIVE: ssl
    depends_on:
      - inventario-service
      - pedidos-service
      - envios-service
      - usuarios-service
    restart: on-failure

  frontend:
    build: ./Frontend
    container_name: smartlogix-frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - gateway-service

volumes:
  postgres_data:
